spring:
  application:
    name: coupon-api

server:
  port: 80
  tomcat:
    mbeanregistry:
      enabled: true

management:
  metrics:
    tags:
      application:
        ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus